### ISSUE TITLE
/var/run/docker.sock is broken

### ISSUE THREAD

**Issue by Bergstein** [jenkinsci/apache-httpcomponents-client-5-api-plugin#29]
### Jenkins and plugins versions report

Can't, NDA.

### What Operating System are you using (both controller, and any agents involved in the problem)?

Linux (Ubuntu)

### Reproduction steps

Setup Docker cloud in Jenkins. 
No special configuration needed.

### Expected Results

Jenkins can access Docker via unix socket, just as the elder gods intended.

### Actual Results

Jenkins can't access Docker via unix socket, elder gods ain't happy.

### Anything else?

First screenshot — 5.2.2-1.1, broken.
Second screen shot — 5.2.1-1.1, works.

![5 2 2-1 1](https://github.com/jenkinsci/apache-httpcomponents-client-5-api-plugin/assets/293768/0da4c7f4-af65-416f-9f0d-c6f6e84239e0)
![5 2 1-1 1](https://github.com/jenkinsci/apache-httpcomponents-client-5-api-plugin/assets/293768/b9058c0a-86a7-4c88-83be-0488172c89ae)

**Comment by strangelookingnerd** [comment]
I guess there is nothing that could be fixed in this plugin since it only provides the dependencies. Maybe there was a (breaking) change in the latest HttpComponents release? We should forwarded this issue to the Docker plugin to validate it and potentially find a fix.

**Comment by basil** [comment]
Fixed in:

- https://github.com/jenkinsci/apache-httpcomponents-client-5-api-plugin/releases/tag/5.4.3-140.v2516ccde99e7
- https://github.com/jenkinsci/docker-java-api-plugin/releases/tag/3.5.0-108.v211cdd21c383
